### ISSUE TITLE
报错“Did not find a query class vip.efactory.modules.system.domain.QUser for domain class vip.efactory.modules.system.domain.User”

### ISSUE THREAD

**Issue by wxb2dyj** [vip-efactory/efadmin#2]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'dataScope' defined in file [/home/wxb/program/efadmin/efadmin-system/target/classes/vip/efactory/config/DataScope.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userServiceImpl': Unsatisfied dependency expressed through field 'br'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userRepository' defined in vip.efactory.modules.system.repository.UserRepository defined in @EnableJpaRepositories declared on MultiTenantJpaConfiguration: Invocation of init method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.jpa.repository.support.QuerydslJpaPredicateExecutor]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: **Did not find a query class vip.efactory.modules.system.domain.QUser for domain class vip.efactory.modules.system.domain.User!**

环境满足文档要求，到处找了都找不到QUser。什么原因？

**Comment by wxb2dyj** [comment]
解决了。clone下来后，需要mvn clean和mvn compile，否则就会出现上面的报错。

**Comment by 1797890817** [comment]
在项目的根目录执行：mvn clean install -DskipTests 
会自动创建出来！
