### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by vancfbruce** [vip-efactory/efadmin#3]
请问，我启动的时候报Parameter 0 of constructor in .system.service.impl.UserServiceImpl required a bean of type '.modules.system.service.mapper.UserMapper' that could not be found. 这个是什么原因导致不能注入的

**Comment by 1797890817** [comment]
请在idea中执行maven clean与maven install 后启动应用

**Comment by 1797890817** [comment]
没有进一步反馈，暂时关闭
